# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SolbegSoftUber' do

pod 'CardIO'
pod 'Masonry'
pod 'Google-Maps-iOS-SDK'
pod 'ECSlidingViewController'
pod 'AFNetworking'

end

